### ISSUE TITLE
Warning: Failed prop type: Invalid prop `theme` of type `string` supplied to `_Editor`, expected `object`.

### ISSUE THREAD

**Issue by StevenCreates** [Kais3rP/react-code-live#2]
I'm just copying and pasting examples right now to get a fill for your package.
and I'm running into this error when trying to pass a theme.

`Warning: Failed prop type: Invalid prop `theme` of type `string` supplied to `_Editor`, expected `object`.`

My code:
`      <Editor
        storageIdentifier="preview-container"
        initialJs={initialReactCode}
        showControls={true}
          theme={{js: "funky", css: "coy"}}
      />`

**Comment by Kais3rP** [comment]
Sorry for the delay, Are you sure you are passing that object as prop? Since that error message looks like you are passing some strings, I gonna check it, but I can't reproduce it right now, I opened a stackblitz to test it: https://stackblitz.com/edit/react-hr4dix and it doesn't have any issue. If you can reproduce it under certain circumstances it could help me to understand the reason. Maybe give a look at the stackblitz and see if you can reproduce the error message there.

**Comment by Kais3rP** [comment]
If you can reproduce the issue I'll reopen it.
